### ISSUE TITLE
Payload drone crash

### ISSUE THREAD

**Issue by Arthur-The-Ok** [MEEPofFaith/prog-mats-java#10]
I deleted the payload and the game crashed.

java.lang.NullPointerException: Cannot assign field "active" because the return value of "progressed.entities.units.entity.DroneUnitEntity.getStation(int, int)" is null
	at progressed.entities.units.entity.DroneUnitEntity.deactivate(DroneUnitEntity.java:144)
	at progressed.entities.units.entity.DroneUnitEntity.kill(DroneUnitEntity.java:139)
	at progressed.entities.units.entity.DroneUnitEntity.update(DroneUnitEntity.java:38)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:59)
	at mindustry.gen.Groups.update(Groups.java:71)
	at mindustry.core.Logic.update(Logic.java:413)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:177)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:166)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:154)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

**Comment by MEEPofFaith** [comment]
What version of PM are you playing?

**Comment by Arthur-The-Ok** [comment]
I downloaded it yesterday

**Comment by MEEPofFaith** [comment]
I made a new release 12 hours ago, yesterday means you're either playing on v17.0 or v17.1, which doesn't help.
Did you download from actions, or did you download from mod browser? Is the mod's version in game v17.0 or v17.1?

**Comment by Arthur-The-Ok** [comment]
I downloaded from the in-gmae browser. The mod's version is V17

**Comment by MEEPofFaith** [comment]
Then you're using an outdated version.
![image](https://user-images.githubusercontent.com/54301439/138156796-eeff2455-50ad-48a8-bb27-9de4deef699c.png)

**Comment by USMP-lancer** [comment]
try to reproduce crash in latest, or close this issue

**Comment by MEEPofFaith** [comment]
stale, closing
