### ISSUE TITLE
Deleting drone pad causes crash

### ISSUE THREAD

**Issue by FlippingPotatoes** [MEEPofFaith/prog-mats-java#8]
If the drone pad has a currently made unit, deleting the pad causes a crash due to a null pointer when the drone attempts to get  their station.

**Comment by FlippingPotatoes** [comment]
It also corrupts the save (often, sometimes the deletion is not saved)

**Comment by MEEPofFaith** [comment]
Give me more info on when you delete the drone pad, as well as give me the crash report.
I don't know what you did, since deleting the drone pad usually kills the drone.

**Comment by FlippingPotatoes** [comment]
Here's a video of the occurrence https://imgur.com/a/O21S1hV

The crash report is as follows:

Mindustry has crashed. How unfortunate.
Version: steam build 132
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
1 Mods: prog-mats:17

java.lang.NullPointerException: Cannot assign field "active" because the return value of "progressed.entities.units.entity.DroneUnitEntity.getStation(int, int)" is null
	at progressed.entities.units.entity.DroneUnitEntity.deactivate(DroneUnitEntity.java:144)
	at progressed.entities.units.entity.DroneUnitEntity.kill(DroneUnitEntity.java:139)
	at progressed.entities.units.entity.DroneUnitEntity.update(DroneUnitEntity.java:38)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:59)
	at mindustry.gen.Groups.update(Groups.java:71)
	at mindustry.core.Logic.update(Logic.java:413)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:177)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:166)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:154)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

**Comment by MEEPofFaith** [comment]
~~wow someone helpful for once~~

Anyways, the commit I just made should fix it.

**Comment by FlippingPotatoes** [comment]
Thanks a lot! Also your mod is awesome :D
